Repository LLNL/RAJA, pull requests merged in 2018-12, with the labels that each got.

#546 Iteration and Tile index/count
  include/RAJA/pattern/kernel/Conditional.hpp
  include/RAJA/pattern/kernel/For.hpp
  include/RAJA/pattern/kernel/Tile.hpp
  include/RAJA/pattern/kernel/internal.hpp
  include/RAJA/policy/cuda/kernel/For.hpp
  include/RAJA/policy/cuda/kernel/Tile.hpp
  test/unit/test-kernel.cpp
Labels: WIP

#548 Removed Shmem and replace with LocalArray
  examples/ltimes.cpp
  include/RAJA/RAJA.hpp
  include/RAJA/pattern/kernel.hpp
  include/RAJA/pattern/kernel/InitLocalMem.hpp
  include/RAJA/pattern/kernel/Tile.hpp
  include/RAJA/pattern/kernel/TileTCount.hpp
  include/RAJA/pattern/shared_memory.hpp
  include/RAJA/policy/cuda.hpp
  include/RAJA/policy/cuda/kernel.hpp
  include/RAJA/policy/cuda/kernel/CudaKernel.hpp
  include/RAJA/policy/cuda/kernel/InitLocalMem.hpp
  include/RAJA/policy/cuda/policy.hpp
  include/RAJA/policy/cuda/shared_memory.hpp
  include/RAJA/policy/openmp/policy.hpp
  include/RAJA/policy/sequential.hpp
  include/RAJA/policy/sequential/policy.hpp
  include/RAJA/policy/sequential/shared_memory.hpp
  include/RAJA/util/LocalArray.hpp
  include/RAJA/util/Permutations.hpp
  include/RAJA/util/ShmemTile.hpp
  include/RAJA/util/StaticLayout.hpp
  test/unit/test-kernel.cpp
  test/unit/test-layout.cpp
  test/unit/test-sharedmem.cpp
Labels: API/usability

#559 Changed plumbing in RAJA::kernel to defer masking off threads until lambda is called
  include/RAJA/policy/cuda/kernel/Conditional.hpp
  include/RAJA/policy/cuda/kernel/CudaKernel.hpp
  include/RAJA/policy/cuda/kernel/For.hpp
  include/RAJA/policy/cuda/kernel/ForICount.hpp
  include/RAJA/policy/cuda/kernel/Hyperplane.hpp
  include/RAJA/policy/cuda/kernel/InitLocalMem.hpp
  include/RAJA/policy/cuda/kernel/Lambda.hpp
  include/RAJA/policy/cuda/kernel/Sync.hpp
  include/RAJA/policy/cuda/kernel/Tile.hpp
  include/RAJA/policy/cuda/kernel/TileTCount.hpp
  include/RAJA/policy/cuda/kernel/internal.hpp
  include/RAJA/policy/cuda/policy.hpp
  test/unit/test-kernel.cpp
Labels: bug
