Repository LLNL/RAJA, pull requests merged in 2020-08, with the labels that each got.

#848 Feature/uberenv
  docs/sphinx/user_guide/developer_guide.rst
  docs/sphinx/user_guide/index.rst
  host-configs/lassen-blueos_3_ppc64le_ib_p9-clang@8.0.1-cuda.cmake
  host-configs/quartz-toss_3_x86_64_ib-clang@9.0.0.cmake
  scripts/uberenv/LICENSE
  scripts/uberenv/Makefile
  scripts/uberenv/README.md
  scripts/uberenv/docs/sphinx/conf.py
  scripts/uberenv/docs/sphinx/index.rst
  scripts/uberenv/gen_spack_env_script.py
  scripts/uberenv/packages/raja/package.py
  scripts/uberenv/project.json
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/compilers.yaml
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib_p9
  scripts/uberenv/spack_configs/config.yaml
  scripts/uberenv/spack_configs/darwin/compilers.yaml
  scripts/uberenv/spack_configs/darwin/packages.yaml
  scripts/uberenv/spack_configs/toss_3_x86_64_ib/compilers.yaml
  scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml
  scripts/uberenv/uberenv.py
Labels: testing

#815 Add omp_for_schedule and omp_for_nowait_schedule policies
  docs/sphinx/user_guide/feature/policies.rst
  include/RAJA/pattern/kernel/Region.hpp
  include/RAJA/policy/openmp/forall.hpp
  include/RAJA/policy/openmp/policy.hpp
  test/include/RAJA_test-forall-execpol.hpp
Labels: feature

#748 Add sort to RAJA
  CMakeLists.txt
  docs/sphinx/user_guide/feature/policies.rst
  docs/sphinx/user_guide/feature/sort.rst
  docs/sphinx/user_guide/features.rst
  docs/sphinx/user_guide/getting_started.rst
  docs/sphinx/user_guide/index.rst
  docs/sphinx/user_guide/tutorial.rst
  docs/sphinx/user_guide/tutorial/sort.rst
  examples/CMakeLists.txt
  examples/tut_sort.cpp
  include/RAJA/RAJA.hpp
  include/RAJA/config.hpp.in
  include/RAJA/internal/MemUtils_CPU.hpp
  include/RAJA/pattern/detail/algorithm.hpp
  include/RAJA/pattern/detail/reduce.hpp
  include/RAJA/pattern/scan.hpp
  include/RAJA/pattern/sort.hpp
  include/RAJA/policy/cuda.hpp
  include/RAJA/policy/cuda/sort.hpp
  include/RAJA/policy/hip.hpp
  include/RAJA/policy/hip/sort.hpp
  include/RAJA/policy/loop.hpp
  include/RAJA/policy/loop/sort.hpp
  include/RAJA/policy/openmp.hpp
  include/RAJA/policy/openmp/scan.hpp
  include/RAJA/policy/openmp/sort.hpp
  include/RAJA/policy/sequential.hpp
  include/RAJA/policy/sequential/sort.hpp
  include/RAJA/policy/tbb.hpp
  include/RAJA/policy/tbb/sort.hpp
  include/RAJA/util/camp_aliases.hpp
  include/RAJA/util/concepts.hpp
  include/RAJA/util/sort.hpp
  include/RAJA/util/zip.hpp
  include/RAJA/util/zip_tuple.hpp
  test/include/RAJA_unit-test-forone.hpp
  test/unit/CMakeLists.txt
  test/unit/algorithm/CMakeLists.txt
  test/unit/algorithm/test-algorithm-sort.cpp.in
  test/unit/algorithm/test-algorithm-stable-sort.cpp.in
  test/unit/algorithm/test-algorithm-util-sort.cpp.in
  test/unit/algorithm/tests/test-algorithm-sort-utils.hpp
  test/unit/algorithm/tests/test-algorithm-sort.hpp
  test/unit/algorithm/tests/test-algorithm-stable-sort.hpp
  test/unit/algorithm/tests/test-algorithm-util-sort.hpp
Labels: WIP, feature
